services:
  backend:
    build: ./backend
    ports:
      - "3030:3030"
    entrypoint:
      [
        "/app/wait-for-it.sh",
        "db:3306",
        "--",
        "/app/start.sh"
      ]
    command: [ "python","app.py" ]
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

         
